-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 18:49:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crudmvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crudmvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `crudmvc`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `ra` INT NULL DEFAULT NULL,
  `curso` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ra` (`ra` ASC) VISIBLE )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crudmvc`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `CPF` CHAR(11) NULL DEFAULT NULL,
  `Data_Nascimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CPF` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crudmvc`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`categoria` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crudmvc`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`livro` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(200) NOT NULL,
  `Editora` VARCHAR(150) NOT NULL,
  `Ano` YEAR NOT NULL,
  `Isbn` VARCHAR(100) NULL DEFAULT NULL,
  `Categoria_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Isbn` (`Isbn` ASC) VISIBLE,
  INDEX `Categoria_Id` (`Categoria_Id` ASC) VISIBLE,
  CONSTRAINT `livro_ibfk_1`
    FOREIGN KEY (`Categoria_Id`)
    REFERENCES `biblioteca`.`categoria` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`autor_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor_livro` (
  `Autor_Id` INT NOT NULL,
  `Livro_Id` INT NOT NULL,
  PRIMARY KEY (`Autor_Id`, `Livro_Id`),
  INDEX `Livro_Id` (`Livro_Id` ASC) VISIBLE,
  CONSTRAINT `autor_livro_ibfk_1`
    FOREIGN KEY (`Autor_Id`)
    REFERENCES `biblioteca`.`autor` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `autor_livro_ibfk_2`
    FOREIGN KEY (`Livro_Id`)
    REFERENCES `biblioteca`.`livro` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crudmvc`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_emprestimo` DATE NOT NULL,
  `data_devolucao` DATE NULL DEFAULT NULL,
  `livro_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `aluno_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `livro_id` (`livro_id` ASC) VISIBLE,
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `aluno_id` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `emprestimo_ibfk_1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `biblioteca`.`livro` (`Id`),
  CONSTRAINT `emprestimo_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `biblioteca`.`usuario` (`id`),
  CONSTRAINT `emprestimo_ibfk_3`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `biblioteca`.`aluno` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
